### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by suman101112** [kmkurn/pytorch-crf#66]
ERROR: Error checking for conflicts.
Traceback (most recent call last):
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in `__getattr__`
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_internal\commands\install.py", line 512, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_internal\operations\check.py", line 114, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_internal\operations\check.py", line 53, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "c:\users\suman\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2736, in requires
    dm = self._dep_map
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3032, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3014, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "c:\users\user\miniconda3\envs\py3_env\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\user\\miniconda3\\envs\\py3_env\\lib\\site-packages\\s3transfer-0.3.3.dist-info\\METADATA'

**Comment by kmkurn** [comment]
The error seems to originate from s3transfer package, as can be seen in the last error message:
```
FileNotFoundError: [Errno 2] No such file or directory: 'c:\users\user\miniconda3\envs\py3_env\lib\site-packages\s3transfer-0.3.3.dist-info\METADATA'
```
Have you tried installing pytorch-crf in a fresh virtual env without installing s3transfer as well?

**Comment by suman101112** [comment]
yes. It installed in a fresh virtual env.
